

AIops2022 = {


    'service_pod': {'currencyservice': ['currencyservice-0',
                                        'currencyservice-2',
                                        'currencyservice2-0',
                                        'currencyservice-1'],
                    'adservice': ['adservice-1', 'adservice-0', 'adservice2-0', 'adservice-2'],
                    'recommendationservice': ['recommendationservice-0',
                                              'recommendationservice2-0',
                                              'recommendationservice-1',
                                              'recommendationservice-2'],
                    'emailservice': ['emailservice-0',
                                     'emailservice-2',
                                     'emailservice-1',
                                     'emailservice2-0'],
                    'checkoutservice': ['checkoutservice-2',
                                        'checkoutservice-0',
                                        'checkoutservice-1',
                                        'checkoutservice2-0'],
                    'frontend': ['frontend2-0', 'frontend-0', 'frontend-2', 'frontend-1'],
                    'cartservice': ['cartservice-1',
                                    'cartservice2-0',
                                    'cartservice-2',
                                    'cartservice-0'],
                    'shippingservice': ['shippingservice-0',
                                        'shippingservice2-0',
                                        'shippingservice-1',
                                        'shippingservice-2'],
                    'productcatalogservice': ['productcatalogservice-2',
                                              'productcatalogservice2-0',
                                              'productcatalogservice-1',
                                              'productcatalogservice-0'],
                    'paymentservice': ['paymentservice-1',
                                       'paymentservice-2',
                                       'paymentservice-0',
                                       'paymentservice2-0']},
    "service_dict": {'adservice': 0,
                     'cartservice': 1,
                     'checkoutservice': 2,
                     'currencyservice': 3,
                     'emailservice': 4,
                     'paymentservice': 5,
                     'productcatalogservice': 6,
                     'recommendationservice': 7,
                     'shippingservice': 8,
                     'frontend': 9},
    'pod_dict': {'currencyservice-1': 0,
                 'adservice-2': 1,
                 'recommendationservice-2': 2,
                 'emailservice2-0': 3,
                 'currencyservice-0': 4,
                 'checkoutservice2-0': 5,
                 'frontend-1': 6,
                 'adservice-1': 7,
                 'frontend2-0': 8,
                 'cartservice-0': 9,
                 'checkoutservice-2': 10,
                 'recommendationservice-0': 11,
                 'shippingservice-2': 12,
                 'shippingservice-0': 13,
                 'productcatalogservice-0': 14,
                 'shippingservice2-0': 15,
                 'paymentservice2-0': 16,
                 'frontend-0': 17,
                 'paymentservice-1': 18,
                 'productcatalogservice-2': 19,
                 'currencyservice-2': 20,
                 'checkoutservice-0': 21,
                 'frontend-2': 22,
                 'paymentservice-2': 23,
                 'recommendationservice2-0': 24,
                 'emailservice-0': 25,
                 'adservice-0': 26,
                 'checkoutservice-1': 27,
                 'paymentservice-0': 28,
                 'recommendationservice-1': 29,
                 'productcatalogservice2-0': 30,
                 'cartservice-1': 31,
                 'adservice2-0': 32,
                 'emailservice-2': 33,
                 'shippingservice-1': 34,
                 'cartservice2-0': 35,
                 'cartservice-2': 36,
                 'productcatalogservice-1': 37,
                 'currencyservice2-0': 38,
                 'emailservice-1': 39},
    'node_dict':{'node-1': 0, 'node-6': 1, 'node-2': 2, 'node-5': 3, 'node-3': 4, 'node-4': 5},
    'template_dict': {'severity info message PaymentService grpc server listening on 50051': 0, 'request servicer_context': 1, 'rpc _channel _InactiveRpcError <_InactiveRpcError of RPC that terminated with': 2, '0': 3, 'onnection to redis was retored successfully': 4, 'File "/usr/local/lib/python3 <*> py" line <*> in <*>': 5, 'response = handler(request servicer_context)': 6, 'ipkin tracing initialized': 7, 'at cartservice cartstore RedisCartStore AddItemAsync(String userId String productId Int32 quantity) in /app/cartstore/RedisCartStore cs line <*>': 8, 'File <*> py" line <*> in <*>': 9, 'EVERE Exception while executing runnable io grpc internal <*>': 10, 'Error reading message': 11, 'self <*> <*>': 12, 'at io grpc <*> <*> <*> java <*>': 13, 'at java util concurrent <*> <*> java <*>': 14, 'eading host address from LISTEN_ADDR environment variable': 15, 'ut of memory': 16, 'severity warning message failed to query product by id dial tcp lookup basic tidb external tidb cluster on <*> 254 20 10 53 no such host': 17, 'etCartAsync called with <*> <*> <*> <*> <*>': 18, 'Request starting HTTP/2 POST http //cartservice 7070/hipstershop <*> application/grpc': 19, 'at Grpc AspNetCore Server Internal PipeExtensions ReadSingleMessageAsync[T](PipeReader input HttpContextServerCallContext serverCallContext Func`2 deserializer)': 20, 'File "/usr/local/lib/python3 7/site <*> py" line <*> in <*>': 21, 'Hosting environment Production': 22, '[40m\x1b[32minfo\x1b[39m\x1b[22m\x1b[49m <*> AspNetCore <*> <*>': 23, 'severity INFO message [Recv ListRecommendations] <*> <*> <*> <*> <*>': 24, 'raceback (most recent call last)': 25, '[40m\x1b[32minfo\x1b[39m\x1b[22m\x1b[49m Microsoft Hosting Lifetime[0]': 26, '<*> <*> <*> <*> failed to upload traces; HTTP status code 503': 27, 'RDB 0 MB of memory used by copy on write': 28, 'Application started Press Ctrl+C to shut down': 29, 'for res in _socket getaddrinfo(host port family type proto flags)': 30, 'return _end_unary_response_blocking(state call False None)': 31, 'return self _base_callable(request timeout metadata credentials)': 32, 'tarted as process with id 1': 33, 'severity warning message failed to retrieve ads': 34, 'severity warning message failed to query product by id driver bad connection': 35, 'at java lang Thread run(Thread java 748)': 36, 'handler': 37, 'at Microsoft AspNetCore Server Kestrel Core Internal Http HttpRequestPipeReader <*> <*>': 38, 'severity warning message failed to query product by id dial tcp lookup basic tidb external tidb cluster on <*> 254 20 10 53 read udp 172 20 <*> <*> <*> <*> 254 20 10 53 i/o timeout': 39, 'Request finished in <*> 200 application/grpc': 40, 'severity info message <*> <*> <*> <*> <*> <*> <*>': 41, 'eading cart service port from PORT environment variable': 42, 'mysql] <*> <*> <*> <*> packets go 37 unexpected EOF': 43, 'severity info message Transaction processed visa ending 0454 Amount <*> <*>': 44, 'status = StatusCode UNAVAILABLE': 45, 'DB saved on disk': 46, 'at Grpc AspNetCore Server Internal CallHandlers ServerCallHandlerBase`3 <HandleCallAsync>g__AwaitHandleCall|8_0(HttpContextServerCallContext serverCallContext Method`2 method Task handleCall)': 47, 'rpc Core RpcException Status(StatusCode="FailedPrecondition" Detail="Can\'t access cart storage StackExchange Redis RedisTimeoutException Timeout awaiting response <*> inbound=0KiB <*> elapsed timeout is 5000ms) <*> next <*> <*> <*> <*> <*> <*> inst 0 qu 0 qs <*> aw False rs ReadAsync ws Idle in 0 in pipe 0 out pipe 0 serverEndpoint redis cart 6379 mc 1/1/0 mgr 10 of 10 available clientName cartservice <*> IOCP (Busy=0 Free=1000 Min=1 Max=1000) WORKER <*> <*> Min=1 Max=32767) v 2 1 58 34321 (Please take a look at this article for some common client side issues that can cause timeouts https //stackexchange github io/StackExchange Redis/Timeouts)': 48, 'at Grpc AspNetCore Server Internal CallHandlers UnaryServerCallHandler`3 HandleCallAsyncCore(HttpContext httpContext HttpContextServerCallContext serverCallContext)': 49, 'Now listening on http //0 0 0 0 7070': 50, 'RROR opentelemetry sdk trace export Exception while exporting Span batch': 51, 'eading redis cache address from environment variable REDIS_ADDR': 52, 'at cartservice CartServiceImpl <*> request ServerCallContext context) in /app/CartServiceImpl cs line <*>': 53, 'at cartservice cartstore RedisCartStore <*> userId) in /app/cartstore/RedisCartStore cs line <*>': 54, 'mall test result OK': 55, 'ava lang NullPointerException': 56, 'severity INFO message A request to send order confirmation email to someone@example com has been received': 57, 'mptyCartAsync called with <*> <*> <*> <*> <*>': 58, 'nsecure mode!': 59, 'Request finished in <*> <*> <*> application/grpc': 60, 'Background saving terminated with success': 61, 'ocket gaierror [Errno <*> <*> <*> <*> <*> <*>': 62, 'at Microsoft AspNetCore Server Kestrel Core Internal Http HttpRequestPipeReader <ValidateState>g__ThrowTaskCanceledException|13_1()': 63, 'self <*>': 64, 'response_or_iterator = behavior(argument context)': 65, 'severity <*> message <*> <*>': 66, "Executed endpoint 'gRPC /hipstershop <*>": 67, "Error status code 'FailedPrecondition' raised": 68, 'ystem IO IOException The client reset the request stream': 69, 'at io grpc <*> <*> java <*>': 70, 'ar <*> 2022 <*> <*> <*> <*> io grpc internal SerializingExecutor run': 71, '<*> Grpc AspNetCore Server <*>': 72, 'request metadata client_info invoker': 73, 'details = "upstream connect error or disconnect/reset before headers reset reason connection failure"': 74, '(self host self port) self timeout self source_address)': 75, 'onnecting to Redis redis cart 6379 ssl=false allowAdmin=true connectRetry=5': 76, "Error when executing service method 'GetCart'": 77, 'raise _InactiveRpcError(state)': 78, 'ddItemAsync called with <*> <*> <*> <*> <*> <*> <*>': 79, 'debug_error_string = "{"created" <*> <*> "description" "Error received from peer ipv4 10 68 16 165 3550" "file" "src/core/lib/surface/call cc" "file_line" 1055 "grpc_message" "upstream connect error or disconnect/reset before headers reset reason connection failure" "grpc_status" 14}"': 80, 'cat_response = product_catalog_stub ListProducts(demo_pb2 Empty())': 81, "Executing endpoint 'gRPC /hipstershop <*>": 82, 'details = "no healthy upstream"': 83, 'details = "upstream connect error or disconnect/reset before headers reset reason connection failure transport failure reason TLS error 268435612 SSL routines OPENSSL_internal HTTP_REQUEST"': 84, 'debug_error_string = "{"created" "@1648106242 608837132" "description" "Error received from peer ipv4 10 68 16 165 3550" "file" "src/core/lib/surface/call cc" "file_line" 1055 "grpc_message" "upstream connect error or disconnect/reset before headers reset reason connection failure transport failure reason TLS error 268435612 SSL routines OPENSSL_internal HTTP_REQUEST" "grpc_status" 14}"': 85, 'result = invoker(request metadata)': 86, 'uccessfully connected to Redis': 87, 'rying to start a grpc server at 0 0 0 0 7070': 88, 'Content root path /app': 89, '<*> changes in <*> seconds Saving': 90, 'severity <*> message <*> <*> <*>': 91, 'erforming small test': 92, 'Background saving started by pid <*>': 93, 'severity info message home': 94, 'for res in getaddrinfo(host port 0 SOCK_STREAM)': 95, 'severity info message payment went through (transaction_id <*> <*> <*> <*> <*>': 96, 'severity info message PaymentService#Charge invoked with request {"amount" {"currency_code" <*> "units" <*> "nanos" <*> "credit_card" {"credit_card_number" "4432 8015 6152 0454" "credit_card_cvv" 672 "credit_card_expiration_year" 2039 "credit_card_expiration_month" 1}}': 97, 'severity warning message failed to send order confirmation to "someone@example com" rpc error code = Canceled desc = context canceled': 98, 'at hipstershop <*> <*> java <*>': 99, 'debug_error_string = "{"created" "@1648106261 658033951" "description" "Error received from peer ipv4 10 68 16 165 3550" "file" "src/core/lib/surface/call cc" "file_line" 1055 "grpc_message" "no healthy upstream" "grpc_status" 14}"': 100, 'self span_exporter export(self spans_list[ idx]) # type ignore': 101, 'luginLoader#load trying to load grpc@1 22 2': 102, 'RROR grpc _server Exception calling application <_InactiveRpcError of RPC that terminated with': 103, 'at Grpc Shared Server UnaryServerMethodInvoker`3 AwaitInvoker(Task`1 invokerTask GrpcActivatorHandle`1 serviceHandle)': 104, 'ystem Threading Tasks TaskCanceledException A task was canceled': 105}

    ,

    'pod_metric_dict': {'container_cpu_cfs_throttled_seconds': 0,
                    'container_cpu_load_average_10s': 1,
                    'container_cpu_system_seconds': 2,
                    'container_cpu_usage_seconds': 3,
                    'container_cpu_user_seconds': 4,
                    'container_file_descriptors': 5,
                    'container_fs_inodes': 6,
                    'container_fs_inodes_free': 7,
                    'container_fs_io_current': 8,
                    'container_fs_io_time_seconds': 9,
                    'container_fs_io_time_weighted_seconds': 10,
                    'container_fs_limit_MB': 11,
                    'container_fs_reads': 12,
                    'container_fs_reads_MB': 13,
                    'container_fs_reads_merged': 14,
                    'container_fs_read_seconds': 15,
                    'container_fs_sector_reads': 16,
                    'container_fs_sector_writes': 17,
                    'container_fs_usage_MB': 18,
                    'container_fs_writes': 19,
                    'container_fs_writes_MB': 20,
                    'container_fs_writes_merged': 21,
                    'container_fs_write_seconds': 22,
                    'container_last_seen': 23,
                    'container_memory_cache': 24,
                    'container_memory_failcnt': 25,
                    'container_memory_failures': 26,
                    'container_memory_mapped_file': 27,
                    'container_memory_max_usage_MB': 28,
                    'container_memory_rss': 29,
                    'container_memory_swap': 30,
                    'container_memory_usage_MB': 31,
                    'container_memory_working_set_MB': 32,
                    'container_network_receive_errors': 33,
                    'container_network_receive_MB': 34,
                    'container_network_receive_packets': 35,
                    'container_network_receive_packets_dropped': 36,
                    'container_network_transmit_errors': 37,
                    'container_network_transmit_MB': 38,
                    'container_network_transmit_packets': 39,
                    'container_network_transmit_packets_dropped': 40,
                    'container_sockets': 41,
                    'container_spec_cpu_period': 42,
                    'container_spec_cpu_quota': 43,
                    'container_spec_cpu_shares': 44,
                    'container_spec_memory_limit_MB': 45,
                    'container_spec_memory_reservation_limit_MB': 46,
                    'container_spec_memory_swap_limit_MB': 47,
                    'container_start_time_seconds': 48,
                    'container_tasks_state': 49,
                    'container_threads': 50,
                    'container_threads_max': 51,
                    'container_ulimits_soft': 52,
                    'container_cpu_cfs_periods': 53,
                    'container_cpu_cfs_throttled_periods': 54},
    'node_metric_dict':{     'system.cpu.iowait': 0,
                         'system.net.bytes_sent': 1,
                         'system.process.zombie.num': 2,
                         'system.io.r_await': 3,
                         'system.load.1': 4,
                         'system.swap.total': 5,
                         'system.io.rkb_s': 6,
                         'system.io.svctm': 7,
                         'system.net.udp.snd_buf_errors': 8,
                         'system.io.util': 9,
                         'system.swap.so': 10,
                         'system.io.w_s': 11,
                         'system.load.15': 12,
                         'system.net.bytes_rcvd': 13,
                         'system.swap.si': 14,
                         'system.load.5': 15,
                         'system.mem.pct_usage': 16,
                         'system.io.w_await': 17,
                         'system.os.nofile.current': 18,
                         'system.net.udp.rcv_buf_errors': 19,
                         'system.net.tcp.in_segs': 20,
                         'system.io.await': 21,
                         'system.net.packets_in.count': 22,
                         'system.net.packets_in.error': 23,
                         'system.net.packets_out.count': 24,
                         'system.os.nofile.used_pct': 25,
                         'system.net.packets_out.error': 26,
                         'system.net.tcp.out_segs': 27,
                         'system.os.nofile.max': 28,
                         'system.net.tcp.retrans_segs': 29,
                         'system.net.udp.in_datagrams': 30,
                         'system.net.udp.in_errors': 31,
                         'system.net.udp.out_datagrams': 32,
                         'system.mem.real.pct_useage': 33,
                         'system.swap.free': 34,
                         'system.mem.total': 35,
                         'system.mem.used': 36,
                         'system.io.avg_q_sz': 37,
                         'system.disk.free': 38,
                         'system.swap.used': 39,
                         'system.swap.used_pct': 40,
                         'system.cpu.user': 41,
                         'system.tcp.retrans_pct': 42,
                         'system.udp.connect.num': 43,
                         'system.disk.total': 44,
                         'system.disk.pct_usage': 45,
                         'system.disk.readonly': 46,
                         'system.disk.used': 47,
                         'system.fs.inodes.free': 48,
                         'system.fs.inodes.in_use': 49,
                         'system.fs.inodes.total': 50,
                         'system.fs.inodes.used': 51,
                         'system.io.r_s': 52,
                         'system.cpu.pct_usage': 53,
                         'system.cpu.system': 54,
                         'system.mem.usable': 55,
                         'system.mem.real.used': 56},
    "service_metric_dict": {
        'rr-http': 0, 'sr-http': 1, 'mrt-http': 2, 'count-http': 3, 'rr-grpc': 4, 'sr-grpc': 5, 'mrt-grpc': 6, 'count-grpc': 7
    },


}
